### ISSUE TITLE
Export taxonomies to Open Semantic Entity Search API

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-ontology-tagger#14]
Analyse and export taxonomy structure from external thesauri/ontologies to Open Semantic Named Entities Search API, so can be used by ETL and UI.

**Comment by Mandalka** [comment]
Implemented for taxonomy of SKOS thesaurus using properties skos:broader and skos:narrower.

**Comment by Mandalka** [comment]
Implemented adding taxonomy for tagging yet indexed documents (for the case you add an ontology after indexing of documents), too.

**Comment by Mandalka** [comment]
Implemented for taxonomies by classes of ontologies by rdf:type and rdfs:subClassOf.
