### ISSUE TITLE
ETL / data enrichment plugin for normalizing/entity linking

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/solr-ontology-tagger#2]
More performant ETL/dataenrichment plugin for normalizing / entity linking of occuring labels.

**Comment by opensemanticsearch** [comment]
Evaluate if SpaCy matcher with some hundred thousands or million of labels is as performant as the running index based matching in Solr, so we can do dictionary based entity recognition / entity linking / normalizing in ETL so it can be used directly without processing in Solr index for ETL to other search index like Elastic Search or graph databases.

**Comment by opensemanticsearch** [comment]
Will be implemented by [ETL plugin ontology-tagger](https://github.com/opensemanticsearch/open-semantic-etl/issues/49)
